labs:
  namespace: lab-rabbitmq-go

  deployment:
    name: rabbitmq-go-producer
    replicas: 2
    repository: aneresdevops/producer-rabbitmq
    tag: f741775
    port: 80

  configmaps: 
    name: rabbitmq-config
    data:
      RMQ_URL: amqp://guest:guest@192.168.5.15:5672/
    
