labs:
  namespace: lab-rabbitmq-go

  deployment:
    name: rabbitmq-go-consumer
    replicas: 2
    repository: aneresdevops/consumer-rabbitmq
    tag: 1.4
    port: 80

  configmaps: 
    name: rabbitmq-config2
    data:
      RMQ_URL: amqp://guest:guest@192.168.5.15:5672/
    
