apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-consumer
  namespace: argocd
spec:
  project: default
  source:
    helm: {}
    repoURL: https://github.com/alan-neres/rabbitmq-send-receive-example.git
    path: lab-go/helm-app/app-consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-rabbitmq-go
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true