apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-07-01T18:44:00Z"
  generation: 2
  labels:
    app: consumer
  name: consumer
  namespace: default
  resourceVersion: "1050626"
  uid: 804e8c8f-2224-4fb9-a30a-4f4b67d67801
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumer
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-rabbitmq
        image: aneresdevops/consumer-rabbitmq:1.4
        imagePullPolicy: IfNotPresent
        name: consumer-rabbitmq
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-02T14:02:16Z"
    lastUpdateTime: "2024-07-02T14:02:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-01T18:44:00Z"
    lastUpdateTime: "2024-07-02T14:27:43Z"
    message: ReplicaSet "consumer-564fbd6b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
