apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumer
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-rabbitmq
        image: aneresdevops/consumer-rabbitmq:1.4
        imagePullPolicy: IfNotPresent
        name: consumer-rabbitmq
       
