apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-message
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-message
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: send-message
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-rabbitmq
        image: aneresdevops/producer-rabbitmq:1.4
        imagePullPolicy: IfNotPresent
        name: producer-rabbitmq
