apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missinkey=error"]
  generators:
  - git:
      repoURL: https://github.com/alan-neres/rabbitmq-send-receive-example.git
      revision: main
      directories:
      - path: lab-go/argocd/applicationset/apps/helm-app/*
  template:
    metadata:
      name: '{{index .path.segments 5}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/alan-neres/rabbitmq-send-receive-example.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 5}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true

