labs:
  namespace: lab-rabbitmq-go

  deployment:
    name: rabbitmq-go-producer
    replicas: 2
    repository: aneresdevops/producer-rabbitmq
    tag: 1.4
    port: 80

  configmaps: 
    name: rabbitmq-config
    data:
      RMQ_URL: amqp://guest:guest@production-rabbitmqcluster.rabbitmq-server.svc.cluster.local:5672/
    
