apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"send-message"},"name":"send-message","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"send-message"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"send-message"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"config-rabbitmq"}}],"image":"aneresdevops/producer-rabbitmq:1.4","imagePullPolicy":"IfNotPresent","name":"producer-rabbitmq","resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2024-07-01T20:20:59Z"
  generation: 3
  labels:
    app: send-message
  name: send-message
  namespace: default
  resourceVersion: "1050434"
  uid: 27e92319-a375-482d-8522-6a00e9b9a424
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: send-message
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: send-message
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-rabbitmq
        image: aneresdevops/producer-rabbitmq:1.4
        imagePullPolicy: IfNotPresent
        name: producer-rabbitmq
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-02T00:21:05Z"
    lastUpdateTime: "2024-07-02T00:21:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-02T14:23:51Z"
    lastUpdateTime: "2024-07-02T14:23:52Z"
    message: ReplicaSet "send-message-7cdd8b7d5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
