apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.name }}
  namespace: {{ .Values.namespace }}
data:
    {{- range $key, $value := .Values.configmaps.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    