name: Push Docker image

on:
  push:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: |
          echo "image_version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "image_name=aneresdevops/producer-rabbitmq" >> $GITHUB_ENV
          image_tag=$(git rev-parse --short HEAD)
          echo TAG=$image_tag >> $GITHUB_OUTPUT
          echo aneresdevops/producer-rabbitmq:$image_tag

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: lab-go/go-app/producer
          push: true
          tags: aneresdevops/producer-rabbitmq:${{ env.image_version }}

  deploy_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run sed 
        env:
          IMAGE_TAG: ${{ needs.push_to_registry.outputs.TAG }}
        run: |
          sed -i 's|{{ image_tag }}|${{ env.IMAGE_TAG }}|g' lab-go/go-app/producer/k8s/deployment.yaml
        
      - name: Commit and push changes
        run: |
          cd lab-go/go-app/producer
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update image tag"
          git push


